# Generated by Django 4.2.6 on 2023-11-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default='Software Engineer', max_length=500),
        ),
    ]
