# Generated by Django 4.2.6 on 2023-11-11 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='Incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskCategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.taskcategory'),
        ),
    ]
